model:
  tier: 1
  layers: [1]
  hidden: 128
  gmm: 10
---
data:
  name: 'airport'
  path: '/mnt/IDMT-WORKSPACE/DATA-STORE/xiaoyg/environment_audio/airport'
  extension: '*.wav'
---
audio:
  sr: 22050
  duration: 10.0
  n_mels: 256
  hop_length: 256
  win_length: 1536
  n_fft: 1536
  num_freq: 541
  ref_level_db: 20.0
  min_level_db: -80.0
---
train:
  num_workers: 4
  optimizer: 'adam'
  sgd:
    lr: 0.0001
    momentum: 0.9
  rmsprop: # from paper
    lr: 0.0001
    momentum: 0.9
  adam:
    lr: 0.0001
  # Gradient Accumulation
  # you'll be specifying batch size with argument of trainer.py
  # (update interval) * (batch size) = (paper's batch size) = 128
  update_interval: 32 # for batch size 1.
---
log:
  summary_interval: 1
  chkpt_dir: '/mnt/IDMT-WORKSPACE/DATA-STORE/xiaoyg/ma_xiaoyg-master/MelNet/chkpt'
  log_dir: '/mnt/IDMT-WORKSPACE/DATA-STORE/xiaoyg/ma_xiaoyg-master/MelNet/logs'
